import random

def generate_random_number():
    """
    This function generates a random between 1 and
    30.

    Returns:
        The number generated
    """
    return random.randint(1, 30)

def check_guess(number_to_guess, user_guess):
    """
    This function compares the user's guess to the number
    randomly generated by the computer.

    Args:
        number_to_guess: The random number generated
        user_guess: The user's guess

    Returns:
        `Too low!` if user guess is less than the random number
        `Too high!` if user guess is greater than the random number
        `Correct!` if user guess is equal to the random number
    """
    if user_guess < number_to_guess:
        return "Too low!"

    elif user_guess > number_to_guess:
        return "Too high!"

    else:
        return "Correct!"

def guess_the_number():
    """
    This function is the main program the is been executed
    """
    number_to_guess = generate_random_number()
    attempts = 0
    guessed_correctly = False
    lifeline = 5

    print("Welcome to 'Guess the Number'!")
    print("I'm thinking of a number between 1 and 30.")
    print(f"You can only make {lifeline} attempts")

    while not guessed_correctly:
        try:
            # User inputs their guess
            user_guess = int(input("Enter your guess: "))
            
            # Increase the number of attempts
            attempts += 1

            # Reduce the lifeline
            lifeline -= 1
            print(f"Lifeline left: {lifeline}")

            result = check_guess(number_to_guess, user_guess)

            print(result)

            # The user can only make 5 attempts to get the right number.
            if attempts <=  4:
                if result == "Correct!":
                    guessed_correctly = True
                    print(f"Congratulations! You guessed the number in {attempts} attempts.")
            else:
                print("Game Over! Attempts exceeded")
                print(f"The number is {number_to_guess}")
                break
        except ValueError:
            print("Please enter a valid integer.")

# Start the game
if __name__ == "__main__":
    guess_the_number()
